### ISSUE TITLE
Feature Request: Add a Notes input

### ISSUE THREAD

**Issue by mclemente** [cs96and/FoundryVYY-release-package#1]
Could you add another input for the Notes URL?

Use case: I don't use a static changelog file, I use the link to the Github release page instead, so my links are dynamic.

**Comment by cs96and** [comment]
f2111092e5f3b2e740e1aaa1b71c6047e4c645fa

**Comment by cs96and** [comment]
Now available in v1.0.2.  If you are just using the `@v1` tag, then you should pick up the change automatically
